# Specify the providers
providers = ["elixir"]

# Setup phase: Include Node.js alongside Elixir/Erlang
[phases.setup]
nixPkgs = ["elixir", "erlang", "nodejs"]

# Build phase: Run the necessary commands
[phases.build]
cmds = [
  "mix local.hex --force",
  "mix local.rebar --force",
  "mix deps.get --only prod",
  "mix compile",
  "cd assets && npm install",  # Install Node.js dependencies
  "mix assets.deploy"
]