# Specify the providers
providers = ["elixir"]

# Setup phase: Include Node.js and Git alongside Elixir/Erlang
[phases.setup]
nixPkgs = ["elixir", "erlang", "nodejs", "git"]

# Build phase: Run the necessary commands
[phases.build]
cmds = [
  "mix local.hex --force",
  "mix local.rebar --force",
  "mix deps.get --only prod",  # This will respect mix.lock
  "mix deps.compile",
  "mix compile",
  "cd assets && npm install",  # Install Node.js dependencies
  "mix assets.deploy"
]

# Start phase
[start]
cmd = "mix phx.server"